// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO8_TbqeUbuqExJyPuIb9MqZODKfzT4ho',
    appId: '1:373967091252:web:dc4dc9fe078734b8ad3c61',
    messagingSenderId: '373967091252',
    projectId: 'fir-app-4fb10',
    authDomain: 'fir-app-4fb10.firebaseapp.com',
    storageBucket: 'fir-app-4fb10.appspot.com',
    measurementId: 'G-V0663QLM9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDEpfDCaAreWqWmbAYKSgtx56lkiGfXHc',
    appId: '1:373967091252:android:07c32ada1dd20096ad3c61',
    messagingSenderId: '373967091252',
    projectId: 'fir-app-4fb10',
    storageBucket: 'fir-app-4fb10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmSN9N-TIn5bUIj143pZCwm8i0QsDEalo',
    appId: '1:373967091252:ios:1a2e42d99ca13a61ad3c61',
    messagingSenderId: '373967091252',
    projectId: 'fir-app-4fb10',
    storageBucket: 'fir-app-4fb10.appspot.com',
    iosClientId: '373967091252-5k62fl1g9smmng8an1ik5okh08ul7c8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.medkitcare',
  );
}
